- name: Install packages for WSL development
  become: True
  become_user: root
  package:
    name: "{{ packages }}"
    state: latest
    update_cache: yes
  vars:
    packages:
      - stow
      - emacs-gtk
      - ispell
      - zsh
      - zsh-doc
      - powerline
      - wl-clipboard
      - direnv

- name: Clone our dotfiles from github
  git:
    repo: https://github.com/dsyzling/dotfiles.git
    dest: ~/dotfiles

- name: Run stow script to install dotfiles
  shell: ./install-wsl.sh
  args:
    chdir: /home/{{ local_username }}/dotfiles
    
- name: Change default shell to ZSH
  shell: sudo chsh -s /usr/bin/zsh dsyzling
  args:
    chdir: /home/{{ local_username }}
   
- name: Install uv for Python
  shell: curl -LsSf https://astral.sh/uv/install.sh | sh
  args:
    chdir: /home/{{ local_username }}

- name: Create template SyncThing directories for Emacs
  shell: |
    mkdir -p ~/Sync/deft
    mkdir -p ~/Sync/todo

#
# Emacs custom build for Wayland and WSL2
# nodejs and npm required to install pyright from within Emacs.
#
- name: Install packages for Custom Emacs Build
  become: True
  become_user: root
  package:
    name: "{{ packages }}"
    state: latest
    update_cache: yes
  vars:
    packages:
      - autoconf
      - texinfo
      - libgtk-3-dev
      - libtiff5-dev
      - libgif-dev
      - libjpeg-dev
      - libpng-dev
      - libxpm-dev
      - libncurses-dev
      - libtiff-dev
      - gnutls-dev
      - imagemagick
      - libtree-sitter-dev
      - libgccjit-13-dev
      - texlive-latex-base
      - texlive-latex-recommended
      - texlive-latex-recommended-doc
      - texlive-science
      - texlive-science-doc
      - texlive-fonts-recommended
      - texlive-fonts-recommended-doc
      - texlive-luatex
      - texlive-xetex
      - nodejs
      - npm

- name: Create pyenv directory for use within Emacs
  shell: |
    mkdir -p ~/.pyenv/versions

- name: Custom Emacs Build
  shell: |
    mkdir ~/dev
    cd ~/dev
    git clone git://git.sv.gnu.org/emacs.git
    cd emacs
    git checkout emacs-29
    ./autogen.sh
    ./configure --with-native-compilation --with-pgtk --with-modules --with-rsvg --with-tree-sitter
    make -j8
    sudo make install
    cd ~/.emacs.d/personal/modules
    gpg --batch --passphrase "{{ dssecretspass }}" --output ds-secrets.el -d ds-secrets.el.gpg
