- name: Install packages for WSL development
  become: True
  become_user: root
  package:
    name: "{{ packages }}"
    state: latest
    update_cache: yes
  vars:
    packages:
      - stow
      - emacs-gtk
      - ispell
      - zsh
      - zsh-doc
      - powerline

- name: Clone our dotfiles from github
  git:
    repo: https://github.com/dsyzling/dotfiles.git
    dest: ~/dotfiles

- name: Run stow script to install dotfiles
  shell: ./install-wsl.sh
  args:
    chdir: /home/{{ local_username }}/dotfiles
    
- name: Change default shell to ZSH
  shell: csh /usr/bin/zsh
  args:
    chdir: /home/{{ local_username }}
   
- name: Install uv for Python
  shell: curl -LsSf https://astral.sh/uv/install.sh | sh
  args:
    chdir: /home/{{ local_username }}
